### PR TITLE
Add cli option to specify the scheduler port

### PR DESCRIPTION
**Pull request by barcode**

### CODE REVIEW

**Comment by barcode** [comment]
It seems Travis uses an older version from icecc (i am using master):
https://github.com/icecc/icecream/blob/0c099f810e66457b37798507d5bd5a96688153d9/services/comm.h#L305

**Comment by krf** [comment]
Note: Icemon is looking for a new maintainer, please check if you'd like to be the person in charge: https://groups.google.com/forum/#!topic/icecream-users/pioozZ-vB0c (just posting this here to raise awareness)

**Comment by llunak** [comment]
The travis build has been updated to use git icecream, so this now should build. Please rebase your request.

**Comment by llunak** [comment]
I've rebased and pushed the commit.

**Pull request closed without merging**
